### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by martindeploy** [shaquiboy/POO-Turnos-Medicos#1]
https://github.com/shaquiboy/POO-Turnos-Medicos/blob/5f8321472d91dbf0b6ac6815eac3d78866a22ea2/TPO%20CLINICA/Model/Main.java#L16

No está bueno que las colecciones se creen afuera de la clínica. Inicializar estas colecciones dentro de clínica.

**Comment by jcfrau** [comment]
- Se realiza la modificacion del constructor en la clase Clínica
- Se realiza la modificacion al inicializar clínica en la clase Main
